created new module named base containing common classes
mertceyhan/bitcoin-market-android pull request #3
Opened 2021-03-22 08:57 UTC by abdalla19977

2021-03-22 17:44 UTC, mertceyhan requested changes

2021-03-22 17:44 UTC, mertceyhan commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Could you remove this? I guess we don't need it.

2021-03-22 17:44 UTC, mertceyhan commented on app/build.gradle.kts
> +    api(project(":base"))
Could you create `Modules` object under `buildSrc` and put this on it? This can be better If we call like that; `api(project(Modules.base))`

2021-03-22 17:44 UTC, mertceyhan commented on .idea/codeStyles/codeStyleConfig.xml
> +    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
Could you remove these changes? We don't want to change codeStyle

2021-03-22 17:44 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/features/market/domain/usecase/MarketInformationUseCaseImpl.kt
> +    override suspend fun getMarketInformation(timespan: MarketInformationTimespan): Flow<com.mertceyhan.bitcoinmarket.base.data.State<MarketInformation>> =
Could you add it as import to the top of the file?

`import com.mertceyhan.bitcoinmarket.base.data.State`

2021-03-22 17:44 UTC, mertceyhan commented on app/src/test/java/com/mertceyhan/bitcoinmarket/core/ui/LayoutViewStateTest.kt
> +    private lateinit var layoutViewState: com.mertceyhan.bitcoinmarket.base.ui.LayoutViewState
Could you add it as import to the top of the file?

`import com.mertceyhan.bitcoinmarket.base.data.State`

2021-03-22 17:44 UTC, mertceyhan commented on app/src/test/java/com/mertceyhan/bitcoinmarket/features/market/ui/MarketViewModelTest.kt
> +    private val layoutViewStateLiveDataObserver = mockk<Observer<com.mertceyhan.bitcoinmarket.base.ui.LayoutViewState>>()
Could you add it as import to the top of the file?

`import com.mertceyhan.bitcoinmarket.base.data.State`

2021-03-22 17:44 UTC, mertceyhan commented on base/.gitignore
> +/build
Could you delete this file? It's looking like unnecessary.

2021-03-22 17:44 UTC, mertceyhan commented on base/build.gradle
> +plugins {
Could you convert it Gradle Kotlin DSL. `build.gradle.kts`
You can get reference from other gradle.kts files.

2021-03-22 17:44 UTC, mertceyhan commented on base/proguard-rules.pro
> +# Add project specific ProGuard rules here.
Could you delete this file? It's looking like unnecessary.

2021-03-22 17:44 UTC, mertceyhan commented on base/src/androidTest/java/com/mertceyhan/bitcoinmarket/base/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
Could you delete this file? It's looking like unnecessary.

2021-03-22 17:44 UTC, mertceyhan commented on base/src/main/java/com/mertceyhan/bitcoinmarket/base/ui/BaseFragment.kt
> -    @LayoutRes
Why do you delete this?

2021-03-22 17:44 UTC, mertceyhan commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
Gradle plugin is already added. We don't need this.

2021-03-22 21:08 UTC, abdalla19977 commented
you can check them now

2021-03-23 22:14 UTC, mertceyhan approved these changes

2021-03-23 22:15 UTC, merged