#25 Added memory cache mechanism
mertceyhan/bitcoin-market-android pull request #35
Opened 2021-12-18 19:42 UTC by barissaglam

2021-12-19 22:07 UTC, barissaglam commented
I will update unit tests

2021-12-19 23:01 UTC, mertceyhan requested changes

2021-12-19 23:01 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/features/market/di/AppModule.kt
> +        "asd", Context.MODE_PRIVATE
Could you change the naming of `SharedPreferences`? The name `asd` doesn't make any sense to me.

2021-12-20 12:03 UTC, barissaglam commented
@mertceyhan Could you  please review again?

2021-12-20 16:36 UTC, mertceyhan commented
Could you check `MarketRepositoryImpTest`, please? @barissaglam

2021-12-20 16:50 UTC, barissaglam commented
> Could you check `MarketRepositoryImpTest`, please? @barissaglam

Could you check again?

2021-12-20 16:55 UTC, mertceyhan approved these changes

2021-12-21 13:27 UTC, merged