add shimmer effect
mertceyhan/bitcoin-market-android pull request #44
Opened 2022-01-17 18:44 UTC by TalhaFaki

2022-01-17 22:16 UTC, mertceyhan commented
Hey @TalhaFaki, thank you so much for your interest in the project and for your contribution.  The shimmer is a good idea but could you check [this library](https://google.github.io/accompanist/placeholder/), please? It looks like a more easy solution.

2022-01-18 07:07 UTC, TalhaFaki commented
Hi @mertceyhan , this lib looks better nice. I will check this day, thanks for feedback.

2022-01-18 17:40 UTC, TalhaFaki commented
Hey @mertceyhan,  I replaced shimmer effect to accompanist shimmer. I hope, better good now.

2022-01-18 21:54 UTC, mertceyhan requested changes

2022-01-18 21:54 UTC, mertceyhan commented on buildSrc/src/main/java/com/mertceyhan/buildsrc/Dependencies.kt
> +    const val accompanist = "com.google.accompanist:accompanist-placeholder:${Versions.accompanist}"
I think `placeholder` would be a better name. `accompanist` is the name of the whole library but we use just place older, right?

`const val placeholder = "com.google.accompanist:accompanist-placeholder:${Versions.placeholderVersion}"`

2022-01-18 21:54 UTC, mertceyhan commented on buildSrc/src/main/java/com/mertceyhan/buildsrc/Versions.kt
> +    const val accompanist = "0.22.0-rc"
`placeholderVersion` would be better.

`const val placeholderVersion = "0.22.0-rc"`

2022-01-18 21:54 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/features/market/ui/MarketScreen.kt
> +fun ScreenContent(scrollState: ScrollState, viewState: MarketScreenViewState? = null, marketViewModel: MarketViewModel, isShowShimmer: Boolean) {
I'm not sure passing null `viewState` to UI 🤔 I think the UI shouldn’t care about the nullability. Do you have a better solution or thought for here?

2022-01-18 21:54 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/core/ui/theme/Color.kt
> +val ShimmerColorShades = listOf(
can we delete this if we don't need?

2022-01-18 21:54 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/core/ui/ShimmerProperty.kt
> +object ShimmerProperty {
I think `PlaceholderProperty` would be better

2022-01-18 21:54 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/components/Chart.kt
> +            )
I think this is too much duplication, maybe we can create our own extension for reducing it.

```
package com.mertceyhan.bitcoinmarket.utils.extensions

import androidx.compose.ui.Modifier
import com.google.accompanist.placeholder.material.placeholder

fun Modifier.placeholder(visible: Boolean) = placeholder(
    visible = visible,
    color = PlaceHolderPromerty.color,
    shape = PlaceHolderPromerty.shape,
    highlight = PlaceHolderPromerty.highlight
)
```

2022-01-18 21:54 UTC, mertceyhan commented on app/src/main/java/com/mertceyhan/bitcoinmarket/components/Chart.kt
> +    isShowShimmer: Boolean
I think `isPlaceHolderVisible` would be more meaningful cause there is no `shimmer` term in `Modifier`. If you agree, could you change all `isShowShimmer` naming to `isPlaceHolderVisible`

2022-01-18 21:58 UTC, mertceyhan commented
Hey @TalhaFaki, I've put some comments on the PR, please mention your thoughts if you disagree. Also, the design looks a bit weird. The application follows CoinMarketCap's design, do you think we can do something similar? If you need help at any point, please ping me. Thanks a lot again, you rock 👏 

![Screenshot_20220118-222513](https://user-images.githubusercontent.com/22434597/150025265-94d55f4e-9f50-4117-b538-fefd2dbec42e.png)
![Screenshot_20220118-222532](https://user-images.githubusercontent.com/22434597/150025268-bee4493e-bd36-48ca-b04e-1df7f79849ca.png)

2022-01-19 06:43 UTC, TalhaFaki commented
Hey @mertceyhan , Thank you very much for all your feedback, I'm closing pr. I'll open it back after a nice refactor.

2022-01-19 06:43 UTC, closed without merging